# coding: utf-8

"""
    Dell APEX Cloud Platform for Microsoft Azure REST API

    Dell APEX Cloud Platform REST API provides a programmatic interface for performing administrative tasks on Dell APEX Cloud Platform for Microsoft Azure. The data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 1.0.000
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ACPAzureSystemInitSpecCloudPlatformManager(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hostname': 'str',
        'ip': 'str',
        'accounts': 'list[TypedAccountSpec]'
    }

    attribute_map = {
        'hostname': 'hostname',
        'ip': 'ip',
        'accounts': 'accounts'
    }

    def __init__(self, hostname=None, ip=None, accounts=None):  # noqa: E501
        """ACPAzureSystemInitSpecCloudPlatformManager - a model defined in Swagger"""  # noqa: E501
        self._hostname = None
        self._ip = None
        self._accounts = None
        self.discriminator = None
        if hostname is not None:
            self.hostname = hostname
        if ip is not None:
            self.ip = ip
        if accounts is not None:
            self.accounts = accounts

    @property
    def hostname(self):
        """Gets the hostname of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501

        The hostname for the APEX Cloud Platform Manager.  # noqa: E501

        :return: The hostname of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this ACPAzureSystemInitSpecCloudPlatformManager.

        The hostname for the APEX Cloud Platform Manager.  # noqa: E501

        :param hostname: The hostname of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def ip(self):
        """Gets the ip of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501

        The IP address for the APEX Cloud Platform Manager.  # noqa: E501

        :return: The ip of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :rtype: str
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this ACPAzureSystemInitSpecCloudPlatformManager.

        The IP address for the APEX Cloud Platform Manager.  # noqa: E501

        :param ip: The ip of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :type: str
        """

        self._ip = ip

    @property
    def accounts(self):
        """Gets the accounts of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501

        Credentials for the APEX Cloud Platform Manager.  # noqa: E501

        :return: The accounts of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :rtype: list[TypedAccountSpec]
        """
        return self._accounts

    @accounts.setter
    def accounts(self, accounts):
        """Sets the accounts of this ACPAzureSystemInitSpecCloudPlatformManager.

        Credentials for the APEX Cloud Platform Manager.  # noqa: E501

        :param accounts: The accounts of this ACPAzureSystemInitSpecCloudPlatformManager.  # noqa: E501
        :type: list[TypedAccountSpec]
        """

        self._accounts = accounts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ACPAzureSystemInitSpecCloudPlatformManager, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ACPAzureSystemInitSpecCloudPlatformManager):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
