# coding: utf-8

"""
    Dell APEX Cloud Platform for Microsoft Azure REST API

    Dell APEX Cloud Platform REST API provides a programmatic interface for performing administrative tasks on Dell APEX Cloud Platform for Microsoft Azure. The data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 1.0.000
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ACPAzureSystemInitSpecGlobalStorage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'configuration_mode': 'str'
    }

    attribute_map = {
        'configuration_mode': 'configuration_mode'
    }

    def __init__(self, configuration_mode=None):  # noqa: E501
        """ACPAzureSystemInitSpecGlobalStorage - a model defined in Swagger"""  # noqa: E501
        self._configuration_mode = None
        self.discriminator = None
        if configuration_mode is not None:
            self.configuration_mode = configuration_mode

    @property
    def configuration_mode(self):
        """Gets the configuration_mode of this ACPAzureSystemInitSpecGlobalStorage.  # noqa: E501

        By default, it is set to EXPRESS. Using EXPRESS will create infrastructure and workload volumes. Using INFRA_ONLY will only create infrastructure volumes. KEEP_STORAGE is used for signle node cluster repair.  # noqa: E501

        :return: The configuration_mode of this ACPAzureSystemInitSpecGlobalStorage.  # noqa: E501
        :rtype: str
        """
        return self._configuration_mode

    @configuration_mode.setter
    def configuration_mode(self, configuration_mode):
        """Sets the configuration_mode of this ACPAzureSystemInitSpecGlobalStorage.

        By default, it is set to EXPRESS. Using EXPRESS will create infrastructure and workload volumes. Using INFRA_ONLY will only create infrastructure volumes. KEEP_STORAGE is used for signle node cluster repair.  # noqa: E501

        :param configuration_mode: The configuration_mode of this ACPAzureSystemInitSpecGlobalStorage.  # noqa: E501
        :type: str
        """
        allowed_values = ["INFRA_ONLY", "EXPRESS", "KEEP_STORAGE"]  # noqa: E501
        if configuration_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `configuration_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(configuration_mode, allowed_values)
            )

        self._configuration_mode = configuration_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ACPAzureSystemInitSpecGlobalStorage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ACPAzureSystemInitSpecGlobalStorage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
