# coding: utf-8

"""
    Dell APEX Cloud Platform for Microsoft Azure REST API

    Dell APEX Cloud Platform REST API provides a programmatic interface for performing administrative tasks on Dell APEX Cloud Platform for Microsoft Azure. The data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 1.0.000
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ACPAzureSystemInitSpecHosts(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'serial_number': 'str',
        'rack': 'ACPAzureSystemInitSpecRack',
        'hostname': 'str',
        'account': 'TypedAccountSpec',
        'management_network_ip': 'str',
        'customer_supplied': 'ACPAzureSystemInitSpecCustomerSupplied'
    }

    attribute_map = {
        'serial_number': 'serial_number',
        'rack': 'rack',
        'hostname': 'hostname',
        'account': 'account',
        'management_network_ip': 'management_network_ip',
        'customer_supplied': 'customer_supplied'
    }

    def __init__(self, serial_number=None, rack=None, hostname=None, account=None, management_network_ip=None, customer_supplied=None):  # noqa: E501
        """ACPAzureSystemInitSpecHosts - a model defined in Swagger"""  # noqa: E501
        self._serial_number = None
        self._rack = None
        self._hostname = None
        self._account = None
        self._management_network_ip = None
        self._customer_supplied = None
        self.discriminator = None
        if serial_number is not None:
            self.serial_number = serial_number
        if rack is not None:
            self.rack = rack
        if hostname is not None:
            self.hostname = hostname
        if account is not None:
            self.account = account
        if management_network_ip is not None:
            self.management_network_ip = management_network_ip
        if customer_supplied is not None:
            self.customer_supplied = customer_supplied

    @property
    def serial_number(self):
        """Gets the serial_number of this ACPAzureSystemInitSpecHosts.  # noqa: E501

        The service tag of the host  # noqa: E501

        :return: The serial_number of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: str
        """
        return self._serial_number

    @serial_number.setter
    def serial_number(self, serial_number):
        """Sets the serial_number of this ACPAzureSystemInitSpecHosts.

        The service tag of the host  # noqa: E501

        :param serial_number: The serial_number of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: str
        """

        self._serial_number = serial_number

    @property
    def rack(self):
        """Gets the rack of this ACPAzureSystemInitSpecHosts.  # noqa: E501


        :return: The rack of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: ACPAzureSystemInitSpecRack
        """
        return self._rack

    @rack.setter
    def rack(self, rack):
        """Sets the rack of this ACPAzureSystemInitSpecHosts.


        :param rack: The rack of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: ACPAzureSystemInitSpecRack
        """

        self._rack = rack

    @property
    def hostname(self):
        """Gets the hostname of this ACPAzureSystemInitSpecHosts.  # noqa: E501

        Name of the host  # noqa: E501

        :return: The hostname of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this ACPAzureSystemInitSpecHosts.

        Name of the host  # noqa: E501

        :param hostname: The hostname of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: str
        """

        self._hostname = hostname

    @property
    def account(self):
        """Gets the account of this ACPAzureSystemInitSpecHosts.  # noqa: E501


        :return: The account of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: TypedAccountSpec
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this ACPAzureSystemInitSpecHosts.


        :param account: The account of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: TypedAccountSpec
        """

        self._account = account

    @property
    def management_network_ip(self):
        """Gets the management_network_ip of this ACPAzureSystemInitSpecHosts.  # noqa: E501

        The IPv4 address of the host to be assigned after OS provision.  # noqa: E501

        :return: The management_network_ip of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: str
        """
        return self._management_network_ip

    @management_network_ip.setter
    def management_network_ip(self, management_network_ip):
        """Sets the management_network_ip of this ACPAzureSystemInitSpecHosts.

        The IPv4 address of the host to be assigned after OS provision.  # noqa: E501

        :param management_network_ip: The management_network_ip of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: str
        """

        self._management_network_ip = management_network_ip

    @property
    def customer_supplied(self):
        """Gets the customer_supplied of this ACPAzureSystemInitSpecHosts.  # noqa: E501


        :return: The customer_supplied of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :rtype: ACPAzureSystemInitSpecCustomerSupplied
        """
        return self._customer_supplied

    @customer_supplied.setter
    def customer_supplied(self, customer_supplied):
        """Sets the customer_supplied of this ACPAzureSystemInitSpecHosts.


        :param customer_supplied: The customer_supplied of this ACPAzureSystemInitSpecHosts.  # noqa: E501
        :type: ACPAzureSystemInitSpecCustomerSupplied
        """

        self._customer_supplied = customer_supplied

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ACPAzureSystemInitSpecHosts, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ACPAzureSystemInitSpecHosts):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
