# coding: utf-8

"""
    Dell APEX Cloud Platform for Microsoft Azure REST API

    Dell APEX Cloud Platform REST API provides a programmatic interface for performing administrative tasks on Dell APEX Cloud Platform for Microsoft Azure. The data is available in JSON format.  # noqa: E501

    OpenAPI spec version: 1.0.000
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IntentSpecVirtualSwitchConfigurationOverrides(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enable_iov': 'bool'
    }

    attribute_map = {
        'enable_iov': 'enable_iov'
    }

    def __init__(self, enable_iov=None):  # noqa: E501
        """IntentSpecVirtualSwitchConfigurationOverrides - a model defined in Swagger"""  # noqa: E501
        self._enable_iov = None
        self.discriminator = None
        if enable_iov is not None:
            self.enable_iov = enable_iov

    @property
    def enable_iov(self):
        """Gets the enable_iov of this IntentSpecVirtualSwitchConfigurationOverrides.  # noqa: E501

        Enable the IO virtualization while creating a virtual switch. The default setting is \"true\".  # noqa: E501

        :return: The enable_iov of this IntentSpecVirtualSwitchConfigurationOverrides.  # noqa: E501
        :rtype: bool
        """
        return self._enable_iov

    @enable_iov.setter
    def enable_iov(self, enable_iov):
        """Sets the enable_iov of this IntentSpecVirtualSwitchConfigurationOverrides.

        Enable the IO virtualization while creating a virtual switch. The default setting is \"true\".  # noqa: E501

        :param enable_iov: The enable_iov of this IntentSpecVirtualSwitchConfigurationOverrides.  # noqa: E501
        :type: bool
        """

        self._enable_iov = enable_iov

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IntentSpecVirtualSwitchConfigurationOverrides, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IntentSpecVirtualSwitchConfigurationOverrides):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
